const express = require('express');
const registerController = require('./register.controller');
const auth=require("./../../config/auth")
const router = express.Router();
router.post('/insertregistration', auth.verifyToken,registerController.insertRegistration);
router.post('/saveorupdatestudentdetails', auth.verifyToken,registerController.saveOrUpdateStudentDetails);
router.post('/getallbatch', auth.verifyToken,registerController.getAllBatch);
router.post('/getallbatchbycourseid', auth.verifyToken,registerController.getAllBatchByCourseId);
router.post('/getallstudentdetails', auth.verifyToken,registerController.getAllStudentDetails);
router.get('/getallyear', auth.verifyToken,registerController.getAllYear);
router.post('/getstudentdetailbyid', auth.verifyToken,registerController.getStudentDetailById);
router.post('/getallregisterdetails', auth.verifyToken,registerController.getAllRegisterDetails);
router.post('/getallregisterstatus', auth.verifyToken,registerController.getAllRegisterStatus);
router.post('/getregisterbyid', auth.verifyToken,registerController.getRegisterById);
router.post('/saveorupdatepaymentdetails', auth.verifyToken,registerController.saveOrUpdatePaymentDetails);
router.post('/getpaymentdetailsbyregisterid', auth.verifyToken,registerController.getPaymentDetailsByRegisterId);
router.post('/getpaymenttype', auth.verifyToken,registerController.getPaymentType);
router.post('/getallpaymentdetails', auth.verifyToken,registerController.getAllPaymentDetails);
router.post('/getallreportdetails', auth.verifyToken,registerController.getAllReportDetails);
router.post('/getallpaymentreportdetails', auth.verifyToken,registerController.getAllPaymentReportDetails);
router.post('/getbarreport', auth.verifyToken,registerController.getBarReport);
router.post('/getbarpaymentreport', auth.verifyToken,registerController.getBarPaymentReport);
router.post('/getcollegewisereport', auth.verifyToken,registerController.getCollegeWiseReport);
router.post('/getcoursewisereport', auth.verifyToken,registerController.getCourseWiseReport);
router.post('/getprojectedreport', auth.verifyToken,registerController.getProjectedReport);
router.post('/getdueamountreport', auth.verifyToken,registerController.getDueAmountReport);
router.post('/getplacementreport', auth.verifyToken,registerController.getPlacementReport);
router.post('/getpaymentdetailsbyid', auth.verifyToken,registerController.getPaymentDetailsById);
module.exports = router;